### ISSUE TITLE
Can't run config --init

### ISSUE THREAD

**Issue by DanielTate** [lucassabreu/clockify-cli#113]
`sudo snap install clockify-cli`

When I run the init command and pass my TOKEN I get the correct workspace but when I press return I get the following error.

```
➜  ~ clockify-cli config --init
? User Generated Token: MY_TOKEN
? Choose default Workspace:
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
github.com/lucassabreu/clockify-cli/cmd.configInit(0xc2e320, 0xc000162830, 0x0, 0x1, 0x0, 0x0)
	/home/runner/work/clockify-cli/clockify-cli/cmd/config.go:172 +0xe1e
github.com/lucassabreu/clockify-cli/cmd.glob..func3(0xc2e320, 0xc000162830, 0x0, 0x1, 0x0, 0x0)
	/home/runner/work/clockify-cli/clockify-cli/cmd/config.go:69 +0x11e
github.com/spf13/cobra.(*Command).execute(0xc2e320, 0xc000162820, 0x1, 0x1, 0xc2e320, 0xc000162820)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc2d6a0, 0x0, 0xc000036060, 0x70)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/lucassabreu/clockify-cli/cmd.Execute(0x99be64, 0x6, 0x9ac420, 0x28, 0x99db40, 0x14)
	/home/runner/work/clockify-cli/clockify-cli/cmd/root.go:51 +0xb2
main.main()
	/home/runner/work/clockify-cli/clockify-cli/main.go:26 +0x69
```

**Comment by DanielTate** [comment]
So I figured it out I needed to type the name of my workspace?

Seems like pressing return should just select the first option?

**Comment by lucassabreu** [comment]
I will try to reproduce it here

**Comment by lucassabreu** [comment]
hi @DanielTate, it was a problem of how the select component i use handle a default value that was not in the list.

in the v0.19.5+ this will be fixed, running a `snap refresh` after a minute or so will solve your problem.
