### ISSUE TITLE
Cannot use bracket in task name

### ISSUE THREAD

**Issue by florianthomi** [lucassabreu/clockify-cli#257]
Hi,

since the last update It's no more possible to use bracket in task name when starting timer. I use it in combination with JIRA task codes and use the brackets to avoid partial task code match.

Here is an example

`clockify-cli in -p 65d30adb66d13c7a0b69sd6b --allow-name-for-id --task "[MP-10]" -i=0`

And this is the stacktrace

```
panic: regexp: Compile(`[mp..*10..*`): error parsing regexp: missing closing ]: `[mp..*10..*`

goroutine 1 [running]:
regexp.MustCompile({0xc000396210, 0xb})
	/opt/hostedtoolcache/go/1.17.13/x64/src/regexp/regexp.go:311 +0xbb
github.com/lucassabreu/clockify-cli/strhlp.IsSimilar({0xc000788098, 0x7})
	/home/runner/work/clockify-cli/clockify-cli/strhlp/strhlp.go:115 +0xf6
github.com/lucassabreu/clockify-cli/pkg/search.findByName({0x7ffd40ddee44, 0x7}, {0x8ca8f6, 0x4}, 0xc00016f050)
	/home/runner/work/clockify-cli/clockify-cli/pkg/search/find.go:29 +0x92
github.com/lucassabreu/clockify-cli/pkg/search.GetTaskByName({0x993aa0, 0xc000039860}, {{0xc000026db0, 0x18}, {0xc0002bfb78, 0x18}, 0x1, {0x0, 0x0}, {0x1, ...}}, ...)
	/home/runner/work/clockify-cli/clockify-cli/pkg/search/task.go:15 +0x74
github.com/lucassabreu/clockify-cli/pkg/cmd/time-entry/util.lookupTask.func1({{0x0, 0x0}, {0xc000026db0, 0x18}, {0xc000026d98, 0x18}, {0xc0002bfb78, 0x18}, {0x0, 0x0}, ...})
	/home/runner/work/clockify-cli/clockify-cli/pkg/cmd/time-entry/util/name-for-id.go:50 +0x15b
github.com/lucassabreu/clockify-cli/pkg/cmd/time-entry/util.compose.func1({{0x0, 0x0}, {0xc000026db0, 0x18}, {0xc000026d98, 0x18}, {0xc0002bfb78, 0x18}, {0x0, 0x0}, ...})
	/home/runner/work/clockify-cli/clockify-cli/pkg/cmd/time-entry/util/util.go:45 +0x135
github.com/lucassabreu/clockify-cli/pkg/cmd/time-entry/util.compose.func1({{0x0, 0x0}, {0xc000026db0, 0x18}, {0xc000026d98, 0x18}, {0x7ffd40ddee10, 0x18}, {0x0, 0x0}, ...})
	/home/runner/work/clockify-cli/clockify-cli/pkg/cmd/time-entry/util/util.go:45 +0x135
github.com/lucassabreu/clockify-cli/pkg/cmd/time-entry/util.Do({{0x0, 0x0}, {0xc000026db0, 0x18}, {0xc000026d98, 0x18}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	/home/runner/work/clockify-cli/clockify-cli/pkg/cmd/time-entry/util/util.go:38 +0xdb
github.com/lucassabreu/clockify-cli/pkg/cmd/time-entry/in.NewCmdIn.func1(0xc0001dd400, {0xc00015b480, 0x0, 0x8})
	/home/runner/work/clockify-cli/clockify-cli/pkg/cmd/time-entry/in/in.go:125 +0x485
github.com/spf13/cobra.(*Command).execute(0xc0001dd400, {0xc00015b400, 0x8, 0x8})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x624
github.com/spf13/cobra.(*Command).ExecuteC(0xc00017ec80)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bc
main.execute()
	/home/runner/work/clockify-cli/clockify-cli/cmd/clockify-cli/main.go:51 +0x125
main.main()
	/home/runner/work/clockify-cli/clockify-cli/cmd/clockify-cli/main.go:31 +0x19
```

I'm on Ubuntu 22.04 and the version of clockify-cli is `Version: 0.48.1, Commit: abbf3bd7577106ca2b252fa1ec96da4ae70d3880, Build At: 2024-02-16T12:34:35Z`

and the Go version `go version go1.22.0 linux/amd64`

Thanks for your feedback

**Comment by lucassabreu** [comment]
hi @florianthomi , sorry for that i fixed it here:
https://github.com/lucassabreu/clockify-cli/releases/tag/v0.48.2

can you try it?

**Comment by florianthomi** [comment]
It seems to be working properly. Thanks for the fix !
